### ISSUE TITLE
Add Telegram Badge To The Readme That Links To The Bot

### ISSUE THREAD

**Issue by RealCerealKiller** [nezorflame/9gag-tbot#1]
Hi @nezorflame,
thank you so much for your awesome Telegram bot. What do you think of adding a badge to the Readme that links to your bot (e.g. [t.me/9gag](https://t.me/9gag))?

**Comment by nezorflame** [comment]
Hi. Bot is not ready yet, but as soon as it gets finished, the link will appear in the README.
